#!/usr/bin/env python

import sys
import hyperopt.mongoexp
import logging

# Add the module to the path since otherwise errors happened during the
# Rasa NLU training.
sys.path.append("/")

logging.basicConfig(stream=sys.stderr, level=logging.INFO)
sys.exit(hyperopt.mongoexp.main_worker())