name: nlu-hyperopt
on: [pull_request]

jobs:
  nlu-hyperopt:
    name: NLU hyperparameter optimization
    runs-on: ubuntu-latest
    outputs:
      best_config: ${{ steps.nluhyperopt.outputs.best_config }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout pull request HEAD commit instead of merge commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: ./
      id: nluhyperopt
      name: Run NLU Hyperoptimization
      with:
        max_evals: 10
        target_metric: f1_score
        search_space: ${{ github.workspace }}/nlu_hyperopt/space.py
